### ISSUE TITLE
Nat Carter | Jasmine

### ISSUE THREAD

**Issue by ngcarter** [ga-wdi-exercises/sweet-libs#79]
I worked alone on Jasmine, a popular JavaScript testing framework. My repository is [here](https://github.com/ngcarter/sweet-libs-jasmine).

Comfort: 4.8 / 5

I would love feedback on my spec/flashcard-spec.js, lines 32-34 comment/question.

**Comment by amaseda** [comment]
Good question. Could there be a case in which for whatever reason `tdd.back` does not contain a string (e.g., a number, array or object)? In that case, having the two tests might be useful.

Otherwise, if you're absolutely certain `tdd.back` will always be a string, then yes maybe the two tests are overkill. But it doesn't hurt to play it safe.

:+1:
